set(OUTPUT_DIR ${CMAKE_SOURCE_DIR})
message("CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}")

# bin shell
file(GLOB SH_SCRIPTS "${CMAKE_SOURCE_DIR}/scripts/*.sh")
install(
  FILES
  ${SH_SCRIPTS}
  PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
  DESTINATION ${CMAKE_INSTALL_PREFIX}
  COMPONENT INSTALL_SHELL_FILES
)